const questions = [
    "Si pudieras vivir en cualquier época histórica, ¿cuál elegirías y por qué?",
    "¿Qué superhéroe o personaje de ficción serías?",
    "¿Cuál es tu palabra o frase favorita en otro idioma y su significado?",
    "Si pudieras crear un festival temático, ¿de qué sería y qué actividades tendría?",
    "¿Algo que te haga reir?",
    "¿Qué habilidad crees que sería más útil en una batalla de globos de agua?",
    "¿Qué personaje histórico o famoso crees que sería el peor camarero/a?",
    "Si tu vida fuera una película, ¿qué género sería y quién te interpretaría?",
    "¿Qué objeto cotidiano te gustaría que tuviera una versión miniatura?",
    "Si tuvieras que dar una conferencia sobre cualquier tema, ¿cuál elegirías y por qué?",
    "¿Cuál es la cosa más loca que has hecho por conseguir un autógrafo o foto con una celebridad?",
    "Si fueras un villano de película, ¿cuál sería tu malvado plan?",
    "¿Cuál sería el título de tu autobiografía?",
    "¿Qué te gustaría que pasara en una fiesta de pijamas perfecta?",
    "Si pudieras diseñar un emoji nuevo, ¿qué expresión o objeto representaría?",
    "¿Cuál es la cosa más extraña o inútil que sabes hacer?",
    "¿Qué harías si pudieras controlar el clima por un día?",
    "¿Qué canción te gustaría que fuera el himno nacional de tu país?",
    "¿Cuál es el objeto más raro que llevas siempre contigo?",
    "¿Qué película te gustaría que tuviera una secuela, incluso si no tiene sentido?",
    "¿Cuál ha sido el mejor meme o chiste de internet que has visto?",
    "¿Qué piensas que hacen los extraterrestres en su tiempo libre?",
    "¿Cuál ha sido la peor moda que has seguido en algún momento?",
    "¿cocinas?¿cuál es tu plato estrella?",
    "¿Cuál sería el nombre de tu propio programa de televisión?",
    "Si pudieras ser un experto en algo instantáneamente, ¿qué elegirías?",
    "¿Qué te gustaría que hubiera en la tienda de tus sueños?",
    "¿Cuál es la cosa más rara que has buscado en internet?",
    "Si fueras un animal, ¿qué animal te gustaría ser y por qué?",
    "¿Qué canción o melodía te gustaría que sea tuya?",
    "¿Cuál ha sido el regalo más inusual que has recibido en tu cumpleaños?",
    "¿Qué canción te hace bailar sin importar dónde estés?",
    "¿Cuál es el lugar más extraño donde has dejado olvidado tu celular?",
    "Si pudieras teletransportarte a cualquier lugar del mundo en este momento, ¿dónde irías?",
    "¿Prefieres vivir sin internet o sin televisión?",
    "¿Qué personaje de película o serie te gustaría ser por un día?",
    "¿Si tuvieras que cambiar tu nombre, cuál elegirías?",
    "¿Te gusta tu nombre?",
    "¿Cual es tu segundo nombre?",
    "¿Cuál es tu comida o postre favorito que te hace sentir como un niño/a otra vez?",
    "¿Qué harías si fueras invisible por un día?",
    "¿Cuál es el objeto más extraño que llevas siempre contigo?",
    "¿Qué canción o género musical te avergüenza que te guste?",
    "Si pudieras vivir en una serie de televisión, ¿cuál sería?",
    "¿Cuál es la actividad más loca que has hecho por diversión?",
    "¿Cuál ha sido el momento más vergonzoso que has vivido?",
    "¿Fuiste a una fiesta de disfraces?¿Cual es el mas raro que usaste?",
    "¿Qué personaje famoso te gustaría tener como vecino/a?",
    "¿Cuál es tu meme o GIF favorito que siempre te hace reír?",
    "¿Si pudieras tener un talento innato, cuál sería?",
    "¿Cuál ha sido la cosa más extraña que has comido?",
    "¿Cuál ha sido la peor película que has visto y te arrepientes de haberla visto?",
    "¿Qué habilidad o talento crees que deberías haber nacido con pero no tienes?",
    "¿Si tuvieras una tienda, qué producto venderías?",
    "Si fueras un juguete, ¿qué juguete te gustaría ser y por qué?",
    "¿Qué te gustaría que fuera posible hacer en la vida real, pero solo es posible en las películas?",
    "¿Qué crees que los extraterrestres piensan sobre nosotros?",
    "¿Qué hábito poco común tienes?",
    "¿Cuál ha sido el mejor apodo que te han puesto?",
    "Si pudieras cambiar tu voz por la de un personaje famoso, ¿cuál elegirías?",
    "¿Cuál es tu peor hábito en la cocina?",
    "¿Cuál es tu talento secreto que nadie sabe?",
    "¿Si tuvieras que tener un robot personal, cómo sería y qué tareas realizaría?",
    "¿Qué harías si ganaras la lotería?",
    "¿Cuál es tu emoji favorito?",
    "¿Qué película podría mejorar si tuviera un final diferente?",
    "¿Cuál ha sido el juguete más extraño que has tenido de niño/a?",
    "Si fueras un personaje de caricatura, ¿cuál serías y por qué?",
    "¿Qué lugar visitado en tus vacaciones te sorprendió positivamente y por qué?",
    "¿Qué lugar visitado en tus vacaciones te sorprendió negativamente y por qué?",
    "¿En que país que no es el actual en el que estas te gustaria vivir?",
    "¿que lugar te gustaria visitar?",
    '¿Playa o montaña?',
    '¿Café o té?',
    '¿Perros o gatos?',
    '¿Libros o películas?',
    '¿Verano o invierno?',
    '¿Pizza o hamburguesa?',
    '¿Mañana o noche?',
    '¿Dulce o salado?',
    '¿Viajar en avión o en coche?',
    '¿Series o peliculas?',
    '¿Cine o concierto?',
    '¿Facebook o Instagram?',
    '¿empanada de jamon y queso o empanada de carne?',
    '¿Pasta o carne?',
    '¿Trabajar desde casa o en la oficina?',
    '¿Nadar en la piscina o en el mar?',
    '¿Caminar o correr?',
    '¿Cocinar en casa o pedir comida a domicilio?',
    '¿Ver una comedia o una película de acción?',
    'Si fueras un director de cine, ¿qué tipo de películas harías y quiénes serían los protagonistas?',
    'Quitando tu trabajo actual...¿A que te dedicarías?',
    'Si fueras un músico, ¿qué género musical tocarías y qué instrumento sería tu favorito?',
    'Si fueras un director de cine. ¿qué tipo de películas harías y cuales serian los roles de los integrantes de esta reuniones?',
    '¿actor/actriz favorito?',
    'En una situación de emergencia, ¿preferirías salvar a un amigo cercano o a un desconocido que está en peligro?',
    'Imagina que estás en una isla desierta, ¿qué tres cosas llevarías contigo para sobrevivir?',
    'Si pudieras viajar en el tiempo, ¿a qué momento histórico irías para intentar cambiar algún evento?',
    'Imagina que hay un incendio en tu casa y solo puedes salvar una cosa, ¿qué objeto escogerías?',
    'Si tuvieras que elegir entre hundirte en un océano lleno de tiburones o en un lago con cocodrilos, ¿cuál sería tu elección y por qué?',
    '¿Rock o Cumbia?',
    '¿Cual es tu canción favorita?',
    '¿Que banda musical fuiste a ver mas veces?',
    '¿Prefieres salir a cenar a un restaurante elegante o pedir comida a domicilio para disfrutar en casa?',
    '¿Elegirías ir al cine a ver la última película de estreno o tener una maratón de series en casa?',
    '¿Preferirías asistir a un concierto de tu banda favorita o a una fiesta temática con amigos?',
    '¿Elegirías ir a un bar con música en vivo o a un club de baile para bailar toda la noche?',
    'Si tenes que aprender a bailar un estilo musical entre salsa y tango ¿cual seria?',
    'Si vas a un bar karaoke y te hacen pasar a cantar ¿que canción cantarias?',
    '¿Te gusta más el vino tinto o el vino blanco?',
    '¿Cerveza o vino?',
    '¿Helado de dulce de leche o de chocolate?',
    '¿Moño o corbata?',
    '¿A que le tenes temes?',
    '¿que caracteristica puede hacer que te caiga mal una persona?',
    '¿un curso que hiciste que no?',
    '¿Que dibujitos mirabas en tu infancia?',
    '¿Qué recuerdos tienes de tu infancia que te hacen sonreír?',
    '¿Cuál era tu comida o postre favorito en la infancia?',
    '¿Tenías algún temor o miedo irracional en la infancia? ¿A qué le tenías miedo?',
    '¿Qué actividad o deporte te gustaba practicar cuando eras niño/a?',
    '¿Como esta compuesta tu familia?',
    '¿Cuál era tu película o película animada favorita cuando eras pequeño/a?',
    '¿Tienes alguna canción o música que te recuerde a tu infancia cada vez que la escuchas?',
    '¿Cuál era tu grupo musical o cantante favorito durante tu adolescencia?',
    '¿Recuerdas alguna película o serie de televisión que marcaron tu adolescencia?',
    '¿Qué tipo de actividades o pasatiempos disfrutabas más durante tu adolescencia?',
    '¿Tenías algún ídolo o modelo a seguir durante tu adolescencia?',
    '¿Cuál era tu materia o asignatura favorita en la escuela secundaria?',
    '¿Cuál era tu materia o asignatura que no te gustaba en la escuela secundaria?',
    '¿Cómo era tu grupo de amigos en la adolescencia? ¿Qué solían hacer juntos?',
    'Si te juntas con amigos ¿Qué suelen hacer juntos?',
    '¿Qué metas o sueños tenías para tu futuro cuando eras adolescente?',
    '¿Qué consejo te darías a ti mismo/a en la adolescencia si pudieras volver atrás en el tiempo?',
    '¿Cuál era tu estilo de moda o tendencias que seguías durante tu adolescencia?'
  ];
  
  function getRandomQuestion() {
    const questionCard = document.getElementById("questionCard");
  
    const randomIndex = Math.floor(Math.random() * questions.length);
    const randomQuestion = questions[randomIndex];
  
    // Crear un nuevo elemento de párrafo para mostrar la pregunta en la card
    const questionElement = document.createElement("p");
    questionElement.textContent = randomQuestion;
  
    // Limpiar las preguntas anteriores antes de agregar la nueva
    questionCard.innerHTML = "";
    questionCard.appendChild(questionElement);
}